[tool.poetry]
name = "energy_manager"
version = "0.3.2"
description = "A simple tool for French consumers having EDF as energy provider, to give them hints on their houses energy consumption based on seasons !!!"
authors = ["Prince Foli Acouetey"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.3.3"
pandas = "^2.2.3"
requests = "^2.32.3"
freezegun = "^1.5.1"
urllib3 = "<2.0"
dvc = "^3.57.0"
dvc-s3 = "^3.2.0"
unidecode = "^1.3.8"
matplotlib = "^3.9.3"
seaborn = "^0.13.2"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
jupyter = "^1.1.1"
myst-nb = {version = "^1.1.2", python = "^3.9"}
sphinx-autoapi = "^3.4.0"
sphinx-rtd-theme = "^3.0.2"
pytest-cov = "^6.0.0"
python-semantic-release = "^9.15.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_toml = ["pyproject.toml:tool.poetry.version",]
branch = "main"
changelog_file = "CHANGELOG.md"
build_command = "pip install poetry && poetry build"