[project]
name = "ticketeer_linux"
authors = [
    {name = "Mikhael Khrustik", email = "misha@myrt.co"},
]
description = "The Linux binaries for ticketeer, commit message utility."
readme = "README.md"
requires-python = ">=3.9"
keywords = ["git", "hook"]
license = {text = "MIT"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: POSIX :: Linux",
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {file = [".version"]}
