[tool.poetry]
name = "lxmfy"
version = "0.2.0"
description = "LXMF bot framework for creating bots for the Reticulum Network"
authors = ["Ivan"]
readme = "README.md"
packages = [{include = "lxmfy"}]

[tool.poetry.dependencies]
python = "^3.13"
lxmf = "^0.5.8"
rns = "^0.8.8"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
lxmfy = "lxmfy.cli:main"
