[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "rangy"
dynamic = ["version",  "description"]
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "Arthur Debert", email = "arthur@debert.xyz" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
urls = { "Homepage" = "https://github.com/arthur-debert/rangy" }

[tool.poetry.dependencies]
python = ">=3.9"

[tool.poetry.group.dev.dependencies]
build = "1.2.2.post1"
asttokens = "2.4.1"
certifi = "2024.6.2"
coverage = "7.6.1"
decorator = "5.1.1"
executing = "2.1.0"
iniconfig = "2.0.0"
ipython = ">=7.0.0"
jedi = "0.19.1"
matplotlib-inline = "0.1.7"
packaging = "24.1"
parso = "0.8.4"
pexpect = "4.9.0"
pluggy = "1.5.0"
prompt-toolkit = "3.0.48" # renamed from prompt_toolkit
ptyprocess = "0.7.0"
pure-eval = "0.2.3"
pyfakefs = "5.7.1"
pygments = "2.18.0"
pytest = "8.3.3"
pytest-cov = "6.0.0"
python-dotenv = "1.0.1"
setuptools = "75.3.0" # Consider removing as poetry manages this
six = "1.16.0"
stack-data = "0.6.3"
traitlets = "5.14.3"
wcwidth = "0.2.13"
pytest-xdist = "3.6.1"
twine = "6.0.1"

[tool.poetry.group.docs.dependencies]
sphinx-rtd-theme = "3.0.2"
sphinxcontrib-applehelp = "2.0.0"
sphinxcontrib-devhelp = "2.0.0"
sphinxcontrib-htmlhelp = "2.1.0"
sphinxcontrib-jquery = "4.1"
sphinxcontrib-jsmath = "1.0.1"
sphinxcontrib-qthelp = "2.0.0"
sphinxcontrib-serializinghtml = "2.0.0"
rstcheck = "6.2.4"
rstcheck-core = "1.2.1"
doc8 = "1.1.2"

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = ["./tests/"]
python_files = ["test_*.py"]
norecursedirs = ["template/py"]

[tool.poetry]
name = "rangy"
version = "1.0.1"
description = "Work with integer ranges with ease"
authors = ["Arthur Debert <arthur@debert.xyz>"]

readme = "README.md"
include = [
    "templates",
    "template/**",
    "LICENSE",
    "README.md"
]
exclude = [
    "tests"
]


[tool.twine]
repository = "https://upload.pypi.org/legacy/"
