[project]
name = "orkestr8-sdk"
version="0.0.188"
requires-python=">=3.8"
authors=[{name="Antsthebul"}]
description="SDK to easily interact with Orkestr8 ML entities"
dependencies=[
    "python-dotenv",
    "boto3"
]
readme="README.md"

[project.scripts]
orkestr8="orkestr8:run"

[project.optional-dependencies]
dev = ["pytest", "pre-commit",  "pytest-cov", "mypy", "notebook"]

[tool.pytest.ini_options]
addopts = "--cov=orkestr8"
