[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "simple-markdown-splitter"
authors = [{name = "Electronic Mango", email = "78230210+Electronic-Mango@users.noreply.github.com"}]
version = "0.4"
description="A simple markdown splitter"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">= 3.11"
keywords = ["markdown", "splitter", "split"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
]

[project.urls]
Homepage = "https://github.com/Electronic-Mango/simple-markdown-splitter"
Documentation = "https://electronic-mango.github.io/simple-markdown-splitter"
Repository = "https://github.com/Electronic-Mango/simple-markdown-splitter"
