[tool.poetry]
name = "cagu-toolkit"
version = "0.1.7"
description = "卡谷电商的工具集合"
authors = ["gongxunyao <eric.gong@caguuu.com>"]
readme = "README.md"
license = "MIT"
packages = [{ include = "cagu_toolkit" }]
include = ["CHANGELOG.md"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = "^3.12"
openai = "1.58.1"
pandas = "2.2.3"
python_dateutil = "2.9.0.post0"
SQLAlchemy = "2.0.36"
tqdm = "4.67.1"
click = "8.1.8"
tabulate = "0.9.0"
requests = "^2.32.3"
pydantic-settings = "^2.7.0"
pymysql = "^1.1.1"
openpyxl = "^3.1.5"

[tool.poetry.scripts]
cagu-toolkit = "cagu_toolkit.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
