[tool.pytest.ini_options]
pythonpath = ["refactor_app"]
env = [
    "TIMEZONE_DELTA = 0",
    "CALIBRATION_CORRECTION = 61.3"
]

[tool.ruff]
# Decrease the maximum line length to 79 characters.
line-length = 100
src = ["refactor_app"]
target-version = "py38"

select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "UP",  # pyupgrade
    "D",   # pydocstyle
    "I",   # isort
]

ignore = ["D101", "D107", "D100", "D102", "D103", "D104", "D105", "D205", "D206"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.black]
line-length = 100


[tool.flake8]
#max-complexity = 12
max-line-length = 100

[tool.poetry]
name = "ecoflight1-producer"
version = "0.1.1"
description = "producers"
authors = ["Yaroslav"]
readme = "README.md"
packages = [
    {include = "refactor_app"}
]

[tool.poetry.dependencies]
python = "^3.8"
pytz = "2021.3"
luma-core = "2.3.1"
minio = "7.2.7"
pydub = "0.25.1"
numpy = "1.24.4"
pyaudio = "0.2.14"
pydantic = "2.0.3"
pytest = "8.3.4"
pydantic-settings = "2.0.3"
aiosqlite = "^0.20.0"
plotly = "^5.24.1"
mypy = "^1.14.0"
acoustics = "^0.2.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
run-noise = "refactor_app.noise_main:main"
run-record = "refactor_app.audio_main:main"