[project]
name = "typed-macro"
version = "0.1.3"
description = "Use procedural macros with type annotations in Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["executing>=2.1.0"]

[tool.ruff.lint]
select = ["ANN"]
ignore = ["ANN401"]

[dependency-groups]
dev = ["pre-commit>=4.0.1", "ruff>=0.8.4"]
