[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "selenium-make"
version = "0.0.2"
authors = [
  { name="Dilraj Singh", email="dilraj082@gmail.com" },
]
description = "A simple CLI tool to set up Selenium scripts and install browser drivers for automation."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
keywords = ["selenium", "chrome", "firefox", "automation", "cli"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
Homepage = "https://github.com/dilrajs616/selenium-make"
Issues = "https://github.com/dilrajs616/selenium-make/discussions"

[project.scripts]
slm = "selenium_make:main"
