[build-system]
requires = [ "setuptools>=62", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "confluent-kafka-config"
version = "1.1.3"
description = "Load all your confluent-kafka clients from config file."
readme = "README.md"
authors = [{ name = "Lazar Jovanovic", email = "l.jovanovic97@gmail.com" }]
license = { file = "LICENSE" }
requires-python = ">=3.12"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Development Status :: 4 - Beta",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.12",
    "Framework :: Pydantic :: 2",
    "Intended Audience :: Developers",
    "Topic :: Utilities",
    "Topic :: System :: Software Distribution"
]
dependencies = [
    "annotated-types==0.7.0",
    "anyio==4.7.0",
    "attrs==24.3.0",
    "avro==1.12.0",
    "build==1.2.2.post1",
    "cachetools==5.5.0",
    "certifi==2024.12.14",
    "charset-normalizer==3.4.0",
    "confluent-kafka==2.6.1",
    "fastavro==1.10.0",
    "h11==0.14.0",
    "httpcore==1.0.7",
    "httpx==0.27.2",
    "idna==3.10",
    "packaging==24.2",
    "pydantic==2.10.4",
    "pydantic-settings==2.7.0",
    "pydantic_core==2.27.2",
    "pyproject_hooks==1.2.0",
    "python-dotenv==1.0.1",
    "PyYAML==6.0.2",
    "requests==2.32.3",
    "setuptools==75.6.0",
    "sniffio==1.3.1",
    "structlog==24.4.0",
    "typing_extensions==4.12.2",
    "urllib3==2.2.3",
]

[project.urls]
Homepage = "https://github.com/Aragonski97/confluent-kafka-config"
Changelog = "https://github.com/Aragonski97/confluent-kafka-config/releases"
Issues = "https://github.com/Aragonski97/confluent-kafka-config/issues"
