[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "f2-commander"
version = "0.5.1"
description = "F2 Commander is an orthodox file manager for the modern world."
license = "MPL-2.0"
authors = ["Timur Rubeko <timcandid@gmail.com>"]
readme = "README.md"
packages = [{include = "f2"}]
homepage = "https://github.com/candidtim/f2-commander"
repository = "https://github.com/candidtim/f2-commander"
keywords = ["file", "manager", "commander"]
classifiers = [
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Environment :: Console",
    "Topic :: Desktop Environment :: File Managers",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/candidtim/f2-commander/issues"

[tool.poetry.dependencies]
python = "^3.9"
textual = "1.0.0"
humanize = "4.11.0"
send2trash = "1.8.3"
platformdirs = "4.3.6"
python-dotenv = "1.0.1"
fsspec = "2024.10.0"
libarchive-c = "5.1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
isort = "^5.13"
flake8 = "^7.1"
mypy = "^1.13"
pytest = "^8.3"
pytest-asyncio = "^0.25.0"
textual-dev = "^1.7"
black = "24.10.0"

[tool.poetry.scripts]
f2 = "f2.main:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"

[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
line_length = 88
profile = 'black'

[tool.mypy]
ignore_missing_imports = true
files = "f2,tests"
