[project]
name = "lb_tech_handler"
version = "1.3.0"
authors = [
  { name = "Johnson Rebeiro", email = "rebeirojohnson@gmail.com" },
]
description = "This package allows faster development by allowing developers to focus on the core logic."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
"requests==2.32.3",
"python-dotenv==1.0.1",
"PyPDF2==3.0.1",
"screeninfo==0.8.1",
"python-barcode==0.15.1",
"Pillow==11.0.0",
"pymsteams==0.2.3"
]

[project.urls]
Homepage = "https://github.com/code-learnbasics/lb_tech_handler"
Issues = "https://github.com/code-learnbasics/lb_tech_handler/issues"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
