[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name="pctheory"
version = "0.0.41"
authors = [
    { name="Jeffrey Martin", email="jmartin@jeffreymartincomposer.com" },
]
description = "A package with functionality for atonal music theory"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "matplotlib",
    "networkx",
    "pyvis",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent"
]

[project.urls]
"Homepage" = "https://fleximeter.github.io/pctheory.html"
