[tool.poetry]
name = "mloptiflow"
version = "0.0.15"
description = "Dynamic MLOps Framework with Integrated CLI for Automated ML Project Inception, Kafka-Driven Real-Time Model Monitoring, and Adaptive Canary Deployment Architectures"
authors = ["Tomas Kozak <tomas.kozak.inv@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://gitlab.com/mloptiflow/mloptiflow"
repository = "https://gitlab.com/mloptiflow/mloptiflow"
include = [
    { path = "mloptiflow/templates/**/*", format = "sdist" }
]


[tool.ruff]
extend = "linter/pyproject.toml"


[tool.poetry.scripts]
mloptiflow = "mloptiflow.cli:cli"
lint = "linter.linter:lint"
"lint:fix" = "linter.linter:lint_fix"
format = "linter.linter:format"
"format:fix" = "linter.linter:format_fix"
"install_git_hooks" = "linter.linter:install_git_hooks"
"precommit" = "linter.linter:precommit"
"fix" = "linter.linter:fix"


[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.0"
click = "^8.1.7"
PyYAML = "^6.0.2"
fastapi = "^0.115.5"
uvicorn = "^0.32.1"


[tool.poetry.group.dev.dependencies]
mypy = "^1.11.2"
pytest = "^8.3.4"
pytest-cov = "^6.0.0"
linter = { path = "linter", develop = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
