[tool.poetry]
name = "danbooru_scraper"
version = "0.1.0"
description = "Scraper for the site danbooru"
authors = ["trojblue <trojblue@gmail.com>"]
license = "MIT"
readme = "README.md"

# cli
[tool.poetry.scripts]
danbooru-scraper = "danbooru_scraper.cli:main"

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.28.1"
beautifulsoup4 = "^4.12.3"
tenacity = "^9.0.0"
tqdm = "^4.67.1"
ipykernel = "^6.29.5"
pip = "^24.3.1"
unibox = "^0.4.13"
s5cmdpy = "^0.2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
