[build-system]
requires = ["setuptools~=68.0.0", "wheel~=0.40.0"]
build-backend = "setuptools.build_meta"

[project]
name              = "dbus_idle"
version           = "2024.12.1"
description       = "System idle time using DBus"
readme            = "README.md"
keywords          = ["dbus_idle", "dbus-idle"]
requires-python   = ">=3.7.0"
authors     = [
    {name="Alexander Frenzel", email="alex@relatedworks.com"},
    {name="bkbilly", email="bkbilly@hotmail.com"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]
dependencies = [
    "dasbus>=1.7",
    "PyGObject>=3.44.0"
]


[project.urls]
"Source Code" = "https://github.com/bkbilly/dbus_idle"

[tool.setuptools.packages.find]
include = ["dbus_idle*"]

[project.scripts]
dbus-idle = "dbus_idle.__main__:main"
