[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=6.3"]
build-backend = "setuptools.build_meta"

[project]
name = "djang-setup"
version = "0.0.6"
description = "A CLI tool to set up Django projects for you"
readme = {file = "readme.md", content-type = "text/markdown"}
requires-python = ">=3.6"
authors = [
    { name = "Yassine", email = "yassine@yassinecodes.dev" }
]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Framework :: Django",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "astor==0.8.1",
    "black==24.10.0",
    "click==8.1.8",
    "rich==13.9.4",
    "django-environ==0.11.2",
]

[project.urls]
Homepage = "https://github.com/fulanii/django_setup"

[project.scripts]
djang-setup = "cli.script:main"