[tool.poetry]
name = "flask-redis-stream-pubsub"
version = "0.1.3"
description = "flask-redis-stream-pubsub"
authors = ["王梓清 <9464553+superwzq1993@user.noreply.gitee.com>"]
readme = "README.md"
homepage = "https://github.com/eininst/flask-redis-stream-pubsub"
documentation = "https://github.com/eininst/flask-redis-stream-pubsub"


[tool.poetry.dependencies]
python = "^3.9"
croniter = "5.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

requires-python = ">=3.9"
dependencies = ["redis>=5.1", "croniter>=5.0.1", "Flask"]
