[tool.poetry]
name = "chapterize-whisper"
version = "0.2.4"
description = ""
authors = ["Jeff Stein <jeffstein@gmail.com>"]
readme = "README.md"
packages = [{include = "chapterize"}]

[tool.poetry.scripts]
chapterize = "chapterize.main:cli"


[tool.poetry.dependencies]
python = "^3.10"
faster-whisper = "^1.1.0"
rich = "^13.9.4"
pydub = "^0.25.1"
mutagen = "^1.47.0"
aiofiles = "^24.1.0"
click = "^8.1.8"
requests = "^2.32.3"


[tool.poetry.group.dev.dependencies]
twine = "^6.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
