[build-system]
requires = ["setuptools>=69.2.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "caluxPy_bc"
version = "0.1.10"
authors = [
  { name = "Luis Manuel Tavarez Valenzuela", email = "luima2494@gmail.com" }
]
maintainers = [
  { name = "Luis Manuel Tavarez Valenzuela", email = "luima2494@gmail.com" }
]
description = "Data Extraction Tool"
readme = "README.md"
license = { file = "LICENSE.txt" }
requires-python = ">=3.11.4"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "datetime>=5.3",
  "numpy>=1.26.4",
  "pandas>=2.2.0",
  "openpyxl>=3.1.2",
]