[project]
name = "docsub"
description = "Update documentation files with external content."
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.9"
dynamic = ["version"]
dependencies = [
  "rich-click~=1.8",
]

[project.scripts]
docsub = "docsub.cli:cli"

[project.urls]
Repository = "https://github.com/makukha/docsub"
Issues = "https://github.com/makukha/docsub/issues"
Changelog = "https://github.com/makukha/docsub/releases"

[dependency-groups]
dev = [
  "pytest~=8.3",
  "pytest-cov~=6.0",
  "pytest-sugar~=1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# bump-my-version

[tool.bumpversion]
current_version = "0.2.0"
allow_dirty = true
files = [
  {filename = "src/docsub/__version__.py"},
]

# hatch

[tool.hatch.version]
path = "src/docsub/__version__.py"

# uv

[tool.uv]
package = true
