[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PyPkiPractice"
version = "1.3.5"
authors = [
    {name = "Laolu Adewoye", email = "laoluadewoye@gmail.com"}
]
description = "A project that, given two input files, can simulate the usage of a Public-Key Infrastructure while devices communicate with each other."
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Internet :: WWW/HTTP"
]
keywords = [
    "Digital Certificates",
    "Public-Key Infrastructure",
    "PKI",
    "Certificate Authorities",
    "Digital Signatures",
    "Encryption",
    "Cryptography",
    "Python",
    "Simulation"
]
requires-python = ">=3.8, <=3.14"
dependencies = [
    "cryptography==44.0.0",
    "PyYAML==6.0.2",
    "tomli==2.2.1",
]

[project.urls]
Repository = "https://github.com/laoluadewoye/PKI_Practice_Python"

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
run-pki-practice = "PKIPractice:run_pki_practice"
