[project]
name = "asf-lib"
version = "0.0.1.5"
requires-python = ">= 3.8"
authors = [
  {name = "Hadar Shavit", email = "shavit@aim.rwth-aachen.de"},
]
maintainers = [
  {name = "Hadar Shavit", email = "shavit@aim.rwth-aachen.de"},
]
description = "Under construction! Algorithm selection framework"
readme = "README.md"
license = {file = "LICENSE"}


