[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "keysvalues"
version = "2.0.5"
description = "Functions for, instead of values and key functions, key-value pairs."
readme = "README.md"
license = {file = "LICENSE"}
authors = [{name = "John Dawson", email = "john.a.dawson@proton.me"}]
maintainers = [{name = "John Dawson", email = "john.a.dawson@proton.me"}]
keywords = [
  "key",
  "keys",
  "sort",
  "sorting",
]

[project.urls]
Homepage = "https://github.com/JohnADawson/keysvalues"
Documentation = "https://github.com/JohnADawson/keysvalues/blob/master/src/keysvalues.py"
