[project]
name = "nonebot_plugin_suggarchat"
version = "0.1.0"
description = "Plugin for the Suggar chat framework compatible with Nonebot2."
authors = [
    { name = "JohnRichard4096", email = "windowserror@163.com" },
]
dependencies = [
    "nonebot-plugin-waiter>=0.6.0",
    "nonebot2",
    "openai",
    "datetime",
    "pyyaml",
    "psutil",
    "loguru>=0.7.2",
    "fastapi>=0.110.2",
    "uvicorn[standard]>=0.28.1",
]
requires-python = ">=3.9"
readme = "README.md"
keywords = [
    "chat",
    "suggar",
    "nonebot",
]

[project.license]
text = "GPL-3.0-or-later"

[project.urls]
Homepage = "https://github.com/JohnRichard4096/nonebot_plugin_suggarchat"
Source = "https://github.com/JohnRichard4096/nonebot_plugin_suggarchat"
"Issue Tracker" = "https://github.com/JohnRichard4096/nonebot_plugin_suggarchat/issues"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true
