[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "URAdime"
version = "0.2.3"
authors = [
    { name="Jason D Limberis", email="Jason.Limberis@ucsf.edu" },
]
description = "Universal Read Analysis of DIMErs"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
keywords = ["PCR", "primers", "DNA", "sequencing", "analysis"]
license = { text = "GPL-3.0" }
dependencies = [
    "pysam",
    "pandas",
    "biopython",
    "python-Levenshtein",
    "tqdm",
    "numpy",
]

[project.urls]
"Homepage" = "https://github.com/SemiQuant/URAdime"
"Bug Tracker" = "https://github.com/SemiQuant/URAdime/issues"

[project.scripts]
uradime = "URAdime.URAdime:main"

[tool.setuptools]
packages = ["URAdime"]