[tool.poetry]
name = "fast-whisper-diarizer"
version = "0.1.8"
description = "A package for audio transcription and speaker diarization using Whisper and NeMo toolkit."
authors = ["Salim <salimkt25@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/salimkt/fast-whisper-diarizer"
homepage = "https://github.com/salimkt/fast-whisper-diarizer"

packages = [{include = "fast_whisper_diarizer"}]

keywords = ["python", "audio", "transcription", "diarization", "whisper", "nemo"]

classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Topic :: Software Development :: Libraries",
  "Topic :: Multimedia :: Sound/Audio :: Analysis",
]

[tool.poetry.scripts]
fast-whisper-diarizer = 'fast_whisper_diarizer.main:main'

[tool.poetry.dependencies]
python = "^3.7"
torch = "2.5.1"
torchaudio = "2.5.1"
numpy = "1.21.0"
faster-whisper = "1.1.0"
ctranslate2 = "4.4.0"
nemo-toolkit = "2.1.0rc0"
omegaconf = "2.3.0"
nltk = "3.9.1"
wget = "3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
