[build-system]
requires = ["setuptools~=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "msklv_openweather_sdk"
version = "1.1.1"
description = "SDK for accessing to OpenWeatherAPI"
readme = "README.md"
authors = [{ name = "Aleksandr Maskalev", email = "avmaskalev@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Development Status :: 5 - Production/Stable",
]
keywords = ["weather", "sdk", "openweather"]
dependencies = [
    "requests>=2.31,<2.33",
]
requires-python = ">=3.7"

[project.optional-dependencies]
dev = ["black", "bumpver", "freezegun", "isort", "pytest"]

[project.urls]
Homepage = "https://github.com/maskalev/openweather_sdk"
Changelog = "https://github.com/maskalev/openweather_sdk/blob/master/CHANGELOG.md"

[tool.bumpver]
current_version = "1.1.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"',
]
"src/openweather_sdk/__init__.py" = [
    '__version__ = "{version}"'
]

[tool.coverage.run]
omit = [
    "*/tests/*"
]