[tool.poetry]
name = "bdax"
version = "0.1.4"
description = "Bayesian Data Analysis using PyMC and JAX"
authors = ["amavrits <amavrist@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
jax = [
    {extras = ['cpu'], version = "^0.4.28", platform  = "win32"},
    {extras = ['cuda'], version = "^0.4.28", platform  = "linux"}
]
chex = "^0.1.86"
distrax = "^0.1.5"
flax = "^0.10.2"
flashbax = "^0.1.2"
jaxtyping = "^0.2.29"
gymnax = "^0.0.6"
jax-tqdm = "^0.2.1"
optax = "^0.2.2"
orbax = "^0.1.9"
blackjax = "^1.2.4"
arviz = "^0.20.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
