[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "openalpha"
version = "0.0.8"
authors = [
  { name="June Nahmgoong", email="june.nahmgoong@openalpha.net" },
]
description = "OpenAlpha Utils"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["numpy","pandas","google-cloud-storage","tqdm"]

[project.urls]
Homepage = "https://github.com/june-nahmgoong/openalpha"
Issues = "https://github.com/june-nahmgoong/openalpha/issues"