[project]
name = "ggrab"
version = "0.1.0a12"
description = "A CLI tool for extracting and sharing code files and functions. A manual context builder for pasting into llms."
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Keizo Gates", email = "keizo@grugnotes.com" }]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.7"
dependencies = [
    "argcomplete",
    "pyperclip",
    "tiktoken",
    "esprima"
]

[project.urls]
Homepage = "https://github.com/keizo/ggrab"
Issues = "https://github.com/keizo/ggrab/issues"

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[project.scripts]
ggrab = "ggrab.ggrab:main"
