[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "new_basic_calculator"
version = "0.1.3"
description = "A basic calculator SDK"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name="snowffer", email="snowffer@xxx.com" }
]
dependencies = [
    "setuptools", "wheel", "twine"
]