[tool.poetry]
name = "burpy-cli"
version = "0.1.1"
description = "A rich tool to create CLI application in python with ease and almost zero dependency on third party packages"
authors = ["MukundSinghRajput <mukundsrajput@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "burpy", from = "src" }
]
keywords = ["cli", "command-line", "framework", "python"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities"
]

[tool.poetry.urls]
"Homepage" = "https://github.com/MukundSinghRajput/burpy-cli"
"Bug Tracker" = "https://github.com/MukundSinghRajput/burpy-cli/issues"

[tool.poetry.scripts]
# Add console script entry point if you have a main CLI entrypoint
# burpy = "burpy.cli:main"

[tool.poetry.dependencies]
python = ">=3.9"
# Add any runtime dependencies here
# For example:
# click = "^8.1.3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-cov = "^5.0.0"
pytest-asyncio = "^0.25.0"
mypy = "^1.14.0"
flake8 = "^7.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "--cov=burpy"