[package]
name = "raksha"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "raksha"
crate-type = ["cdylib"]

[dependencies]
logos = "0.15.0"
pyo3 = { version = "0.23.3", features = ["abi3-py310"] }
strum = { version = "0.26.3", features = ["derive", "strum_macros"] }
